# Generated by Django 4.1.4 on 2023-01-25 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("to_do_list", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="time_clear",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
