# Generated by Django 4.1.5 on 2023-01-23 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="care",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="images"),
        ),
        migrations.AlterField(
            model_name="care", name="place", field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="care", name="title", field=models.CharField(max_length=10),
        ),
    ]
