# Generated by Django 4.1.5 on 2023-01-23 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0002_alter_care_photo_alter_care_place_alter_care_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="care",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="photos/"),
        ),
    ]
