# Generated by Django 4.1.5 on 2023-01-23 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0003_alter_care_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="care",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
