# Generated by Django 4.1.5 on 2023-01-24 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0004_alter_care_photo"),
    ]

    operations = [
        migrations.RemoveField(model_name="care", name="photo",),
        migrations.AddField(
            model_name="care",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="", verbose_name="이미지"
            ),
        ),
    ]
