# Generated by Django 4.1.5 on 2023-01-25 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0007_alter_care_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="care",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="", verbose_name="이미지"
            ),
        ),
    ]
